name: modern_form_popupmenu
description: PopUpMenu customized.
version: 2.1.0
repository: https://github.com/apps-auth/modern_form_popupmenu
homepage: https://github.com/apps-auth/modern_form_popupmenu

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.32.4"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

#flutter: